### ISSUE TITLE
Where can I find 'search_mp3_frame.js' file?

### ISSUE THREAD

**Issue by freegemini** [hhd-software/hex-editor-definition-library#1]
https://github.com/hhd-software/hex-editor-definition-library/blob/2342c360cbf228e5aed95d1f4311fbe20ddd171c/h/mp3.h#L12C17-L12C36
There is no such file in `AppData\Roaming\HHD Software\Hex Editor Neo\Sample Structures\h\`

**Comment by AlexBAV** [comment]
We've added the missing files.

Could you please switch to the "Commit channel" and test the latest commit?
